sudo: required
language: python3.6
services:
  - docker
env:
  global:
    - IMAGE=nthienan/jenkins
    - VERSION=1
install: true

script:
  - ./builder.sh build $IMAGE $VERSION
after_success:
  - docker images

before_deploy:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
deploy:
  - provider: script
    script: ./builder.sh deploy $IMAGE $VERSION
    on:
      branch: master
after_deploy:
  - docker images
