apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    role: master
    component: ci-cd
spec:
  selector:
    app: jenkins
    role: master
    component: ci-cd
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: jnlp
    protocol: TCP
    port: 50000
    targetPort: 50000
  type: LoadBalancer
