credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: devops
          username: devops
          password: s0m3thingS3cr3t
          description: "General user used for demo purpose"
